name: CI workflow
workflow triggers: push on main branch and pull_request on main branch
Jobs
runs-on: ubuntu-latest
container: python:3.9-slim
Checkout step:
name: Checkout
uses: actions/checkout@v3
Install Dependencies step:
name: Install dependencies
run python -m pip install --upgrade pip and pip install -r requirements.txt commands
